// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// piecewise_quadratic
List piecewise_quadratic(NumericMatrix coef, NumericVector b);
RcppExport SEXP _SIRA_piecewise_quadratic(SEXP coefSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(piecewise_quadratic(coef, b));
    return rcpp_result_gen;
END_RCPP
}
// bracket_quadratic
List bracket_quadratic(NumericMatrix coef, NumericVector a, NumericVector b);
RcppExport SEXP _SIRA_bracket_quadratic(SEXP coefSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(bracket_quadratic(coef, a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SIRA_piecewise_quadratic", (DL_FUNC) &_SIRA_piecewise_quadratic, 2},
    {"_SIRA_bracket_quadratic", (DL_FUNC) &_SIRA_bracket_quadratic, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SIRA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
