# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

piecewise_quadratic <- function(coef, b) {
    .Call(`_SIRA_piecewise_quadratic`, coef, b)
}

bracket_quadratic <- function(coef, a = as.numeric( c()), b = as.numeric( c())) {
    .Call(`_SIRA_bracket_quadratic`, coef, a, b)
}

